name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nginx and Curl
        run: |
          echo "HOLA MUNDO" >> hola.txt
          cat hola.txt
          