name: CHECKOUT

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - run: |
          if [ -f "script.sh" ]; then
            chmod +x script.sh
            ./script.sh
          fi