name: NODEJS

on: [push]

jobs:
  others:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: List files
        run: ls -al

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      - name: Print Node.js version
        run: node --version
    