name: NODEJS

on: [push]

jobs:
  others:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: DDDD
        uses: ../.github/actions/my-action