name: NODEJS

on: [push]

jobs:
  others:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: List files
        run: ls -al

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      - name: Print Node.js version
        run: node --version

      - name: PHP
        uses: shivammathur/setup-php@v2
        witch:
          php-version: '8.3'
      
      - name: php version
        run: php --version
    