name: NODEJS

on: [push]

jobs:
  others:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Enlistar
        uses: ls -al  
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      - name: Node version
        run: node --version
      
    