name: NODEJS

on: [push]

jobs:
  others:
    runs-on: ubuntu-lastest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
    
    - name: node version
      run: node --version
    