name: HOLA MUNDO

on: [push]

jobs: 
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: HOLA MUNDO
      run: echo "Hola Mundo" 
    
    - name: touch file
     run: touch hola.txt 

    - name: set text
     run: echo "PRUEBA 2" >> hola.txt 

    - name: Read file
     run: cat hola.txt

  otro:
    runs-on: ubuntu-latest

    steps: 
    - name: LS
      run: ls -al